In [22]:
import sqlalchemy
import pandas as pd
import os

In [34]:
HOST = 'localhost'
PORT = '5432'
DATABASE = 'northwind_3'
USER = 'rjt.weber'
PASSWORD = os.getenv('POSTGRES_PASSWORD')

In [35]:
conn_string = f'postgres://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}'

In [37]:
engine = sqlalchemy.create_engine(conn_string)

In [38]:
engine.table_names()

['customers',
 'categories',
 'regions',
 'employee_territories',
 'employees',
 'order_details',
 'orders',
 'products',
 'shippers',
 'suppliers',
 'territories',
 'best_customer_table']

In [20]:
result = engine.execute('select * from customers')

In [21]:
pd.DataFrame(result)

,0,1,2,3,4,5,6,7,8,9,10
0,ALFKI,Alfreds Futterkiste,Maria Anders,Sales Representative,Obere Str. 57,Berlin,None,12209,Germany,030-0074321,030-0076545
1,ANATR,Ana Trujillo Emparedados y helados,Ana Trujillo,Owner,Avda. de la Constitución 2222,México D.F.,None,05021,Mexico,(5) 555-4729,(5) 555-3745
2,ANTON,Antonio Moreno Taquería,Antonio Moreno,Owner,Mataderos 2312,México D.F.,None,05023,Mexico,(5) 555-3932,None
3,AROUT,Around the Horn,Thomas Hardy,Sales Representative,120 Hanover Sq.,London,None,WA1 1DP,UK,(171) 555-7788,(171) 555-6750
4,BERGS,Berglunds snabbköp,Christina Berglund,Order Administrator,Berguvsvägen 8,Luleå,None,S-958 22,Sweden,0921-12 34 65,0921-12 34 67
...,...,...,...,...,...,...,...,...,...,...,...
86,WARTH,Wartian Herkku,Pirkko Koskitalo,Accounting Manager,Torikatu 38,Oulu,None,90110,Finland,981-443655,981-443655
87,WELLI,Wellington Importadora,Paula Parente,Sales Manager,Rua do Mercado 12,Resende,SP,08737-363,Brazil,(14) 555-8122,None
88,WHITC,White Clover Markets,Karl Jablonski,Owner,305 - 14th Ave. S. Suite 3B,Seattle,WA,98128,USA,(206) 555-4112,(206) 555-4115
89,WILMK,Wilman Kala,Matti Karttunen,Owner/Marketing Assistant,Keskuskatu 45,Helsinki,None,21240,Finland,90-224 8858,90-224 8858
90,WOLZA,Wolski Zajazd,Zbyszek Piestrzeniewicz,Owner,ul. Filtrowa 68,Warszawa,None,01-012,Poland,(26) 642-7012,(26) 642-7012